# This is a basic workflow to help you get started with Actions

name: Build and Deploy on website Cpanel (via ftp)

# Controls when the action will run. 
on:
  push:
    branches: [ master ]
  # Triggers the workflow on push or pull request events but only for the main branch
  # schedule:
  #     - cron:  '0 5,10,15,20,0 * * *'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: npm install

    - name: Build
      run: npm build

    - name: 📂 Sync files in website Cpanel via FTP
      uses: SamKirkland/FTP-Deploy-Action@4.0.0
      with:
        server: ftp.bitaraes.com.br
        username: u827606196.github
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: build/
        server-dir: public_html/
